name: "Quotes"
main: net.twasiplugin.quotes.QuotesPlugin
author: "Twasi Team"
version: 1.0
description: "Always remember your favorite quotes!"
commands:
  - quote
permissions:
  - net.twasi.quotes.read
  - net.twasi.quotes.manage