name: "Quotes"
main: net.twasiplugin.quotes.QuotesPlugin
author: "Twasi Team"
version: 1.0
description: "Always remember your favorite quotes!"
commands:
  - quote
permissions:
  - net.twasi.quotes.read
  - net.twasi.quotes.manage

api: |
  type Quotes {
    publicAll(name: String): [Quote]
  }

  type Quote {
    id: String,
    numId: Int,
    content: String,
    createdAt: String,
    game: String,
    reporter: String
  }